frr version 8
frr defaults traditional
hostname dc2-cluster-forge-a
log syslog informational
service integrated-vtysh-config
!
bfd
 profile initrode
  detect-multiplier 3
  receive-interval 150
  transmit-interval 150
 !
!
bfd
 profile umbrella
  detect-multiplier 3
  receive-interval 200
  transmit-interval 200
 !
!
! --- initrode (VLAN 100, vrf-initrode) ---
router bgp 65004 vrf vrf-initrode
 bgp router-id 203.0.113.2
 bgp graceful-restart
 neighbor 203.0.113.1 remote-as 65005
 neighbor 203.0.113.1 bfd profile initrode
 !
 address-family ipv4 unicast
  network 10.21.0.0/24
 exit-address-family
!
! --- umbrella (VLAN 101, vrf-umbrella) ---
router bgp 65005 vrf vrf-umbrella
 bgp router-id 203.0.113.6
 bgp graceful-restart
 neighbor 203.0.113.5 remote-as 65005
 neighbor 203.0.113.5 bfd profile umbrella
 !
 address-family ipv4 unicast
  network 10.21.1.0/24
 exit-address-family
!
line vty
!