frr version 8
frr defaults traditional
hostname dc1-cluster-forge-b
log syslog informational
service integrated-vtysh-config
!
bfd
 profile acme-staging
  detect-multiplier 3
  receive-interval 150
  transmit-interval 150
 !
!
bfd
 profile globex-staging
  detect-multiplier 3
  receive-interval 100
  transmit-interval 100
 !
!
! --- acme-staging (VLAN 100, vrf-acme-staging) ---
router bgp 65101 vrf vrf-acme-staging
 bgp router-id 192.0.2.2
 bgp graceful-restart
 neighbor 192.0.2.1 remote-as 65100
 neighbor 192.0.2.1 bfd profile acme-staging
 !
 address-family ipv4 unicast
  network 10.40.0.0/24
 exit-address-family
!
! --- globex-staging (VLAN 101, vrf-globex-staging) ---
router bgp 65102 vrf vrf-globex-staging
 bgp router-id 192.0.2.6
 bgp graceful-restart
 neighbor 192.0.2.5 remote-as 65100
 neighbor 192.0.2.5 bfd profile globex-staging
 !
 address-family ipv4 unicast
  network 10.40.1.0/24
 exit-address-family
!
line vty
!