apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/cluster-infra

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: migration-uplink-policy
    patch: |-
      - op: replace
        path: /spec/nodeSelector/frr-bootc.io~1cluster
        value: cluster-forge-b

labels:
  - includeSelectors: false
    pairs:
      frr-bootc.io/cluster: cluster-forge-b
