frr version 8
frr defaults traditional
hostname dc1-cluster-forge-a
log syslog informational
service integrated-vtysh-config
!
bfd
 profile acme
  detect-multiplier 3
  receive-interval 150
  transmit-interval 150
 !
!
bfd
 profile globex
  detect-multiplier 3
  receive-interval 100
  transmit-interval 100
 !
!
bfd
 profile initech
  detect-multiplier 3
  receive-interval 300
  transmit-interval 300
 !
!
! --- acme (VLAN 100, vrf-acme) ---
ip prefix-list PL-acme-IN seq 10 permit 198.51.100.0/24 le 32
router bgp 65001 vrf vrf-acme
 bgp router-id 198.51.100.2
 bgp graceful-restart
 neighbor 198.51.100.1 remote-as 65000
 neighbor 198.51.100.1 bfd profile acme
 !
 address-family ipv4 unicast
  network 10.20.0.0/24
  neighbor 198.51.100.1 prefix-list PL-acme-IN in
 exit-address-family
!
! --- globex (VLAN 101, vrf-globex) ---
router bgp 65002 vrf vrf-globex
 bgp router-id 198.51.100.6
 bgp graceful-restart
 neighbor 198.51.100.5 remote-as 65000
 neighbor 198.51.100.5 bfd profile globex
 !
 address-family ipv4 unicast
  network 10.20.1.0/24
 exit-address-family
!
! --- initech (VLAN 102, vrf-initech) ---
router bgp 65003 vrf vrf-initech
 bgp router-id 198.51.100.10
 bgp graceful-restart
 neighbor 198.51.100.9 remote-as 65000
 neighbor 198.51.100.9 bfd profile initech
 !
 address-family ipv4 unicast
  network 10.20.2.0/24
  network 10.20.3.0/24
  aggregate-address 10.20.2.0/23 summary-only
 exit-address-family
!
line vty
!