apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: frr-bootc

resources:
  - ../../../../base
  - generated/virtualmachines/virtualmachines.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: frr-config
    files:
      - generated/frr-config/daemons
      - generated/frr-config/frr.conf
      - generated/frr-config/vtysh.conf
  - name: network-config
    files:
      - generated/network-config/interfaces.yaml
      - generated/network-config/nmstate.yml

patches:
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: trunk-br0-policy
    patch: |-
      - op: replace
        path: /spec/nodeSelector/frr-bootc.io~1site
        value: dc2
  - target:
      kind: NodeNetworkConfigurationPolicy
      name: frr-peering-uplink-policy
    patch: |-
      - op: replace
        path: /spec/nodeSelector/frr-bootc.io~1site
        value: dc2
  - target:
      kind: NetworkAttachmentDefinition
      name: frr-peering
    patch: |-
      - op: replace
        path: /spec/config
        value: |
          {
            "cniVersion": "0.4.0",
            "name": "frr-peering",
            "type": "ovn-k8s-cni-overlay",
            "topology": "layer2",
            "subnets": "10.10.2.0/24",
            "mtu": 1500,
            "netAttachDefName": "frr-bootc/frr-peering",
            "allowPersistentIPs": true
          }

labels:
  - includeSelectors: false
    pairs:
      frr-bootc.io/cluster: cluster-forge-a
      frr-bootc.io/site: dc2
